# server information
[server]
brokerId = "Area2"
port = 5559
granularity = 5
messageProcessors = 2

    [server.mode]
    name = "disgb_publisherMatching"
    brokerAreaFilePath = "/home/mbar/Desktop/geobroker/GeoBroker-Server/src/main/resources/broker_areas.json"
    brokerCommunicators = 2

